# Version management for TestTone
# This file centralizes version information

file(READ "${CMAKE_SOURCE_DIR}/VERSION" TESTTONE_VERSION_STRING)
string(STRIP "${TESTTONE_VERSION_STRING}" TESTTONE_VERSION_STRING)

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-(.+))?$" VERSION_MATCH "${TESTTONE_VERSION_STRING}")

if(VERSION_MATCH)
    set(TESTTONE_VERSION_MAJOR ${CMAKE_MATCH_1})
    set(TESTTONE_VERSION_MINOR ${CMAKE_MATCH_2})
    set(TESTTONE_VERSION_PATCH ${CMAKE_MATCH_3})

    if(CMAKE_MATCH_5)
        set(TESTTONE_VERSION_SUFFIX ${CMAKE_MATCH_5})
        set(TESTTONE_VERSION_FULL "${TESTTONE_VERSION_MAJOR}.${TESTTONE_VERSION_MINOR}.${TESTTONE_VERSION_PATCH}-${TESTTONE_VERSION_SUFFIX}")
    else()
        set(TESTTONE_VERSION_SUFFIX "")
        set(TESTTONE_VERSION_FULL "${TESTTONE_VERSION_MAJOR}.${TESTTONE_VERSION_MINOR}.${TESTTONE_VERSION_PATCH}")
    endif()
else()
    message(FATAL_ERROR "Invalid version format in VERSION file: ${TESTTONE_VERSION_STRING}")
endif()

set(PROJECT_VERSION "${TESTTONE_VERSION_MAJOR}.${TESTTONE_VERSION_MINOR}.${TESTTONE_VERSION_PATCH}")
set(PROJECT_VERSION_MAJOR ${TESTTONE_VERSION_MAJOR})
set(PROJECT_VERSION_MINOR ${TESTTONE_VERSION_MINOR})
set(PROJECT_VERSION_PATCH ${TESTTONE_VERSION_PATCH})

if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(TESTTONE_VERSION ${TESTTONE_VERSION_FULL} PARENT_SCOPE)
endif()

message(STATUS "TestTone Version: ${TESTTONE_VERSION_FULL}")
message(STATUS "  Major: ${TESTTONE_VERSION_MAJOR}")
message(STATUS "  Minor: ${TESTTONE_VERSION_MINOR}")
message(STATUS "  Patch: ${TESTTONE_VERSION_PATCH}")
if(TESTTONE_VERSION_SUFFIX)
    message(STATUS "  Suffix: ${TESTTONE_VERSION_SUFFIX}")
endif()
